# energyforecast

> Helper functions for the energy forecast project.

In [ ]:
# | default_exp energyforecast

In [ ]:
# | hide
# | exporti
from nbdev.showdoc import *
import polars as pl
import matplotlib.pyplot as plt
import pandas as pd

import requests
import csv
from io import StringIO
from datetime import datetime

In [ ]:
# | export
def aemo_price_demand(state: str, year: int, month: int):
    assert isinstance(month, int) and isinstance(year, int)
    assert (
        year >= 1998 and year <= datetime.now().year
    ), "Year must be from 1998 to current year"
    assert month >= 1 and month <= 12, "Month between 1 to 12"

    if month < 10:
        month_str = f"0{month}"
    else:
        month_str = str(month)

    state = state.lower()

    # TODO: closest match / fuzzy match
    state_code_map = {"vic": "VIC1", "nsw": "NSW1"}

    state_code = state_code_map[state]
    try:
        url = f"https://aemo.com.au/aemo/data/nem/priceanddemand/PRICE_AND_DEMAND_{year}{month_str}_{state_code}.csv"
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        }
        response = requests.get(url, headers=headers)

        response.raise_for_status()  # Check for any errors in the response
        csv_content = StringIO(response.text)
    except:
        pass

    return pd.read_csv(csv_content, parse_dates=True)

In [ ]:
aemo_price_demand("vic", 2023, 1)

     REGION       SETTLEMENTDATE  TOTALDEMAND     RRP PERIODTYPE
0      VIC1  2023/01/01 00:05:00      4676.57  129.51      TRADE
1      VIC1  2023/01/01 00:10:00      4722.43  124.72      TRADE
2      VIC1  2023/01/01 00:15:00      4672.63  111.64      TRADE
3      VIC1  2023/01/01 00:20:00      4616.49  110.75      TRADE
4      VIC1  2023/01/01 00:25:00      4604.27  110.91      TRADE
...     ...                  ...          ...     ...        ...
8923   VIC1  2023/01/31 23:40:00      4664.75  115.28      TRADE
8924   VIC1  2023/01/31 23:45:00      4670.26  111.10      TRADE
8925   VIC1  2023/01/31 23:50:00      4575.90  110.00      TRADE
8926   VIC1  2023/01/31 23:55:00      4565.74  108.91      TRADE
8927   VIC1  2023/02/01 00:00:00      4575.72  116.09      TRADE

[8928 rows x 5 columns]